### ISSUE TITLE
Missing bower.json file

### ISSUE THREAD

**Issue by henrikix** [maciel310/angular-filesystem#7]

**Comment by andreicojea** [comment]
Created pull request, I hope it's all good :-)

**Comment by maciel310** [comment]
Thanks for the contribution!

**Comment by andreicojea** [comment]
You're welcome ^_^

**Comment by andreicojea** [comment]
Hey @maciel310, I just realised the git tags were not included in the pull request. Therefore, bower doesn't receive the right version. Apparently only the repo owner can do this, so please run the following commands:

```
git tag -a v0.1.1
git push --tags
```

Cheers!
