### ISSUE TITLE
Warning in Chrome Version 41.0.2267.0 dev (64-bit) OSX

### ISSUE THREAD

**Issue by pastuxso** [maciel310/angular-filesystem#8]
```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
```

**Comment by maciel310** [comment]
Thanks for the report. I'll try and take a look at this when I can, but since I'm not actively using this library for any projects I'm not sure how quickly I'll be able to get to this.

If anyone can provide a pull request I'd happily merge it in.

**Comment by gweedo767** [comment]
Resolved by this pull request:
https://github.com/maciel310/angular-filesystem/pull/11
